title: Stephen Ajulu
baseURL: https://stephenajulu8.netlify.app

paginate: 6
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
author:
  name: Stephen Ajulu
languageCode: en-us
watch: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
    - JSON

taxonomies:
  tag: tags
  category: categories

related:
  threshold: 20
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 80
    - name: date
      weight: 10
