title: Stephen Ajulu
baseURL: https://stephenajulu.com
markup:
  goldmark:
    renderer:
      unsafe: true
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
author:
  name: Stephen Ajulu
languageCode: en-us
watch: true
